### ISSUE TITLE
Restrict @bot.group roles to #assign-yourself-ranks

### ISSUE THREAD

**Issue by sudo-deus** [Zevphyr/Balerion#1]
Simple issue for newcomers; It should only be about one or two lines of code. Don't worry about getting the channel ID (leave it as (id=id))

Refer to https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html

To solve.

**Comment by ghost** [comment]
Would a decorator solve this issue by using something like `@is_channel('channel_id')`

**Comment by sudo-deus** [comment]
You are very close and on the right track. If you crawl through the documents a bit then there's actually something like that in there and that's what we want to use.

This would point you closer to the right direction https://discordpy.readthedocs.io/en/v1.0.1/api.html#discord.Guild.channels

**Comment by sudo-deus** [comment]
Like I said, you were on the right track and super close.  I added it when I got back home tonight, however, so there's no need of it anymore. Feel free to look at how I wrote it -- and keep learning!

**Comment by ghost** [comment]
Where did you get the value for each of the keys and what do they do? 


```
roles_dict = {'python': 572081414007423016, 'c++': 572081414007423016, 'java': 572081491291668481,
'web': 572081500875653150}
```

**Comment by sudo-deus** [comment]
@wazdat 

So, each value is an ID for a discord role. They can be fetched through the discord api, however, the easier way to retrieve them is to enable developer mode in discord and mention the role -- you must put a back-slash though.

Like so: `\@discordrole` 
which will then come out as `<&[id]>` where [id] is an integer and the only thing you want to copy.

Using these ID's lets us communicate with the discord api that we are specifically assigning the role that id is linked too. Make sense?
