### ISSUE TITLE
Role command not listed under help

### ISSUE THREAD

**Issue by sudo-deus** [Zevphyr/Balerion#12]
Compare: 
`@commands.command(name='role', brief='Assigns or removes roles')`
To:
`@modules.command(name='load', hidden=True, brief='Command which Loads a module.')`

And yet, even without the `hidden=True`, the first line [(Located here)](https://github.com/Zevphyr/Balerion/blob/6033a9799133574bb3ff651d69a9d71a039a86ae/Balerion/cogs/role.py#L15) is hidden when the help command is called. 

This should not be the case. The role command and description should appear when help is called. 
@mikejgray

**Comment by mikejgray** [comment]
Suspected it may be related to versions, or that "hidden=True" was a default parameter, but struck out there so far. Continuing to troubleshoot.

**Comment by sudo-deus** [comment]
Oof, I just figured it out. Because I am using a check to see whether or not the command can be run in the channel, the command also won't show up when called with /help, unless it's called within the channel /role is allowed to be used.
