### ISSUE TITLE
Pause and Resume

### ISSUE THREAD

**Issue by sudo-deus** [Zevphyr/Balerion#25]
It would be a nice QOL addition to have a pause and resume playback option when streaming audio with the bot.

I want two new, separate, commands in the MusicCog. One with the name `pause` assigned to it and the other, by `resume`. They should both be case insensitive and only work inside a voice channel.

Refer to these links for assistance: 

https://github.com/Rapptz/discord.py
https://discordpy.readthedocs.io/en/latest/api.html#voice

**Comment by davidazael** [comment]
I will work on this @Zevphyr

**Comment by sudo-deus** [comment]
Good luck! Let me know if you have any further questions., at any time. :)

**Comment by sudo-deus** [comment]
Issue resolved. :)
