### ISSUE TITLE
Welcome New Members

### ISSUE THREAD

**Issue by sudo-deus** [Zevphyr/Balerion#29]
Have the bot welcome new members to the server, in the "introduce-yourself" channel, and ask them to give a brief introduction.

The bot should mention the new user; the message sent should be restricted to only one channel; and should send a brief message welcoming the new user to the server- with a channel link to "assign-yourself-ranks".

The code should be in a separate cog, able to be loaded onto the bot via "initial_extensions".

https://github.com/Rapptz/discord.py
https://discordpy.readthedocs.io/en/latest/

**Comment by lringham** [comment]
Hello, I would like to tackle this issue.

**Comment by sudo-deus** [comment]
Resolved!
