### ISSUE TITLE
Purge Traceback

### ISSUE THREAD

**Issue by sudo-deus** [Zevphyr/Balerion#4]
Functional, however, Usage prompts:

 `discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Message`

Minor problem so I'm not too worried about it but if anyone wants to take a look at it and tackle it, go  ahead.

Refer to issue #2

**Comment by ghost** [comment]
Is this fixed?

**Comment by sudo-deus** [comment]
No! Its not fixed yet :)

The error means that either the channel or the message was not found. 

So, It actually might not even be an issue considering the purpose of the command is to delete messages.
