### ISSUE TITLE
Double Response

### ISSUE THREAD

**Issue by sudo-deus** [Zevphyr/Balerion#8]
Bot sends the help message twice and furthermore, replies twice to every command; worse even, the first response list the available commands whilst the second responds that said commands do not exist.

1. Go to the discord
2. type /help
3. See error

Bot should be responding only once and should be listing all commands that are not hidden.

Somewhere, some function is calling the bot twice. We need to find that.

**Comment by mikejgray** [comment]
Hiya, looking for different projects to start contributing to, and I've built a Discord bot of my own for a friend's D&D game. I experienced similar issues when I had multiple instances of the code running simultaneously. I joined the Discord server and typed /help but haven't seen any issues...is this an ongoing problem?

**Comment by sudo-deus** [comment]
Ah, hello there! Definitely welcome to contribute where you can :)
I've already fixed this issue -- I just haven't be on to close it; turns out it was connected to my problem 
when loading the cogs. But, I still need someone to make some examples as listed in one of the open issues.
